# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-10-25 14:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('df_goods', '0002_auto_20171025_2214'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='goodsinfo',
            options={'ordering': ['-id'], 'verbose_name': '商品', 'verbose_name_plural': '商品'},
        ),
        migrations.AlterModelOptions(
            name='typeinfo',
            options={'ordering': ['-id'], 'verbose_name': '分类', 'verbose_name_plural': '分类'},
        ),
    ]
