# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-10-28 02:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('df_goods', '0004_auto_20171025_2249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goodsinfo',
            name='gclick',
            field=models.IntegerField(default=1000, verbose_name='点击量'),
        ),
        migrations.AlterField(
            model_name='goodsinfo',
            name='gprice',
            field=models.DecimalField(decimal_places=2, default=20.0, max_digits=5, verbose_name='价格'),
        ),
        migrations.AlterField(
            model_name='goodsinfo',
            name='gstock',
            field=models.IntegerField(default=500, verbose_name='库存'),
        ),
    ]
