# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-10-28 04:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('df_goods', '0005_auto_20171028_1014'),
    ]

    operations = [
        migrations.RenameField(
            model_name='goodsinfo',
            old_name='gadv',
            new_name='gcom',
        ),
    ]
