# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-10-28 04:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('df_goods', '0006_auto_20171028_1204'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdvInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apic', models.ImageField(upload_to='adv', verbose_name='广告图片')),
                ('acom', models.BooleanField(default=False, verbose_name='是否推荐')),
            ],
            options={
                'verbose_name_plural': '广告',
                'verbose_name': '广告',
            },
        ),
    ]
